### ISSUE TITLE
Docs regarding creating models

### ISSUE THREAD

**Issue by additop78** [hsynlms/sequelize-fastify#14]
I decided to go ahead with this plugin, only to find out that there's no documentation telling how and where to define models. 
There is a `define` method available on the instance, but however that doesn't help as there's no elaborate constructor or method to define models. Please help.

**Comment by hsynlms** [comment]
Hi @additop78 

Actually this is a plugin which allows you to integrate and use Sequelize with Fastify. You need to check [Sequelize documentation](https://sequelize.org) for all of your questions.
