### ISSUE TITLE
Why is the fastify.close() method in successful connection?

### ISSUE THREAD

**Issue by santi1428** [hsynlms/sequelize-fastify#6]
I removed that line of code and It started working again.

**Comment by hsynlms** [comment]
It's an example file which shows a message in the console and closes Fastify server and Sequelize.

You do not need to use the example file in your project.

**Comment by santi1428** [comment]
> It's an example file which shows a message in the console and closes Fastify server and Sequelize.
> 
> You do not need to use the example file in your project.

Ok I understand, thank you very much for the plugin.

**Comment by hsynlms** [comment]
@santi1428 thank you, glad to hear that!
